### ISSUE TITLE
Bug: Concurrent editing at beginning of text is not commutative

### ISSUE THREAD

**Issue by ehuas** [yorkie-team/yorkie#559]
**Description**:
When two peers edit concurrently at the beginning of a text block, the result is not the same. See test case in _tree_test.ts_, 'Can insert text to the same position(left) concurrently'. We expect result 'BA12', but in some cases we get result 'AB12'. 

We found that this is due to incorrect tree logic when finding the correct position to insert while merging the two copies. Current logic can be found in the _edit_ function as well as the _findTreePosWithSplit_ function in _crdt/tree.ts_

**Discussion**
We discussed two potential changes to the algorithm. The first is a minor change, while the second requires further evaluation of plausibility and algorithmic efficiency.

(1) Right now, insertion can happen before an element (if offset == 0) in **insertBefore** operations, or after an element (if offset == 1) in **insertAfter** operations. Say we want to merge 'B12' and 'A12', where we are inserting the changed element 'A' into 'B12'. Let's call 'A' **changed**. We could change our algorithm so that we only allow **insertAfter** operations, and start the range of potential places for insertion from one element before **changed**. In our example, the range would start from the _dummy head_, and we would want to insert after 'B'. In the reverse case, where we are inserting 'B' into 'A12', we would start from the _dummy head_ as well, and we would want to insert right after the dummy head, to create a final result of 'BA12' in both situations.

(2) The second option is to convert the underlying tree structure into a linked list, so that RGATreeSplit operations can be used. The potential problems with this option are (a) the time it takes to constantly convert from a tree to a list back to a tree and (b) how to execute the conversion from list structure back into tree structure.

**Comment by krapie** [comment]
Is there any progress on this issue?

**Comment by ehuas** [comment]
> Is there any progress on this issue?

we're currently working on it! right now we're implementing the first option.

**Comment by hackerwins** [comment]
# Tasks
- [x] Go SDK: https://github.com/yorkie-team/yorkie/pull/607
- [x] JS SDK: https://github.com/yorkie-team/yorkie-js-sdk/pull/611
- [x] Android SDK: https://github.com/yorkie-team/yorkie-android-sdk/pull/131
- [x] iOS SDK: https://github.com/yorkie-team/yorkie-ios-sdk/pull/102
