### ISSUE TITLE
Versioned Document Schema & Validation

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#971]
**Description**:

Currently, Yorkie allows developers to express their application models using a Document that adheres to a specific schema. While each SDK takes advantage of type safety features provided by their respective languages(e.g. [TypeScript Support](https://yorkie.dev/docs/js-sdk#typescript-support)), developers frequently need to modify these schemas when updating application versions. 

To better manage data reliably according to these varying schemas, it is essential to implement a system where developers can define and migrate Document schemas by version. Providing a feature in the Dashboard for defining versioned document schemas will address this need.

Moreover, it would be beneficial to refer to the Schema Validation feature in Liveblocks during the design and implementation phases. More information can be found [here](https://liveblocks.io/docs/platform/schema-validation).

<img width="686" alt="Screenshot 2024-08-20 at 6 25 00 PM" src="https://github.com/user-attachments/assets/6318c356-b27a-4ed6-b206-b95867de9851">

**Why**:

This enhancement would provide a structured approach to handle schema changes, enabling developers to manage their data more efficiently across different versions of their applications.

**Comment by blurfx** [comment]
I'm interested in this topic, can I get involved?

**Comment by hackerwins** [comment]
## Task List

### JSON Element Schema Validation

- [x] JSON Element Schema Definition
  - [x] Define JSON Element grammar: [yorkie-schema](https://github.com/yorkie-team/yorkie-schema)
- [x] JSON Element Schema Validator
  - [x] Implement cycle detection: [Test](https://github.com/yorkie-team/yorkie-schema/blob/5627a9fbc11ef78ec22b54ea265b83438966da64/test/schema.test.ts#L248-L261)
  - [x] Restrict unused type definition: [Test](https://github.com/yorkie-team/yorkie-schema/blob/5627a9fbc11ef78ec22b54ea265b83438966da64/test/schema.test.ts#L239-L246)

### Change Validator Development

- [x] Ruleset Converter(`Schema -> Ruleset`), Ruleset Validator(`Document.Update`)
  - [x] Primitive
  - [x] Object
    - [x] Optional Properties
  - [x] Array
  - [x] Yorkie.Counter
  - [x] Yorkie.Text
  - [x] Yorkie.Tree
- [x] Document Update Validation
  - [x] Implement validation logic for changes based on Root and Rules
  - Local updates that violate the schema throw an error.

### Version Management

- [x] SDK Interface: [js-sdk](https://github.com/yorkie-team/yorkie-js-sdk/pull/1010)
  - Implement client attachment with schema
  - Example: `client.attach(doc1, {schema: "schema@1"})`
- [x] Version & Schema API: [yorkie](https://github.com/yorkie-team/yorkie/pull/1345)
  - Schema Storage and Loading
  - Handle Schema-Document Lifecycle
  - Verify document compatibility with new schema attachments
  - Schema-Document Attachment API

### Dashboard Development

- [x] Wireframe Creation
  - Reference: [Liveblocks schema validation](https://liveblocks.io/docs/platform/schema-validation)
  - Implement basic components
- [x] Schema Page: [dashboard](https://github.com/yorkie-team/dashboard/pull/226)
  - [x] Create Schema
  - [x] Update Schema
  - [x] Delete Schema
  - [x] Schema list 
  - [x] Show the linked schema for each document on the document page
  - [ ] Show which documents are using each schema on the schema page


### Tree Element Schema Validation

- [x] Tree Element Schema Definition
  - Define tree element grammar in yorkie-schema
  - Implement new tree element grammar similar to [ProseMirror schema example](https://prosemirror.net/examples/schema/)
- [x] Tree Element Validator
- [ ] Error Event Handler
    - For more complex cases like schema conflicts, error events allow custom handling.
- [ ] Test with real documents in CodePair and Wafflebase

### Documentation

- [x] Design Documentation
- [ ] User Documentation
- [ ] JS SDK Examples

### Contributors:
- @chacha912, @sigmaith, @blurfx, @hackerwins
